"""
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter
at a random position.

Find the letter that was added in t.

Example:

    Input:
    s = "abcd"
    t = "abcde"
    
    Output:
    e
    
    Explanation:
    'e' is the letter that was added.
"""
class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        if s is None or s == "":
            return t
        count = collections.defaultdict(int)
        for c in s:
            count[c] += 1
        soln = []
        for c in t:
            if count[c] == 0:
                soln.append(c)
            else:
                count[c] -= 1
        return "".join(soln)

import collections
a = Solution()
print(a.findTheDifference('abcd', 'abcactedde'))
